/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfata;

import javax.swing.UIManager;
import liste.*;

/**
 *
 * @author HP
 */
public class MainWindow extends javax.swing.JFrame {

    Lista<Integer> L;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        this.setLocationRelativeTo(null);

        L = new Lista<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit_Button = new javax.swing.JButton();
        list_TextField = new javax.swing.JTextField();
        addLast_Button = new javax.swing.JButton();
        deleteFirst_Button = new javax.swing.JButton();
        addDelete_TextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        exit_Button.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        exit_Button.setForeground(new java.awt.Color(128, 0, 0));
        exit_Button.setText("EXIT");
        exit_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_ButtonMouseClicked(evt);
            }
        });

        list_TextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        addLast_Button.setText("Add Last");
        addLast_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLast_ButtonActionPerformed(evt);
            }
        });

        deleteFirst_Button.setText("delete First");
        deleteFirst_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFirst_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exit_Button))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addLast_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteFirst_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDelete_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 200, Short.MAX_VALUE))
                    .addComponent(list_TextField))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                .addComponent(list_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLast_Button)
                    .addComponent(deleteFirst_Button)
                    .addComponent(addDelete_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_ButtonMouseClicked
        this.setVisible(false);
        //this.dispose();
        System.exit(0);
    }//GEN-LAST:event_exit_ButtonMouseClicked

    private void addLast_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLast_ButtonActionPerformed
        Integer i = null;

        try {
            i = Integer.parseInt(addDelete_TextField.getText());
        } catch (NumberFormatException nfe) {
            i = null;
        }
        if(i != null){
            L.addLast(new Nod<>(i));
        
        list_TextField.setText(L.getListAsString());
        }
    }//GEN-LAST:event_addLast_ButtonActionPerformed

    private void deleteFirst_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFirst_ButtonActionPerformed
        
        L.deleteFirst();
        list_TextField.setText(L.getListAsString());
    }//GEN-LAST:event_deleteFirst_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addDelete_TextField;
    private javax.swing.JButton addLast_Button;
    private javax.swing.JButton deleteFirst_Button;
    private javax.swing.JButton exit_Button;
    private javax.swing.JTextField list_TextField;
    // End of variables declaration//GEN-END:variables
}
